build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
    # complexity: 2
    # LongParameterList: 1
    # style: 1
    # comments: 1

complexity:
  active: true
  CyclomaticComplexMethod:
    active: true
    threshold: 4
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 6
  LargeClass:
    active: true
    threshold: 150

style:
  active: true
  MagicNumber:
    active: true
    ignoreNumbers: ['-1', '0', '1', '2']
